### ISSUE TITLE
issues running tracts2

### ISSUE THREAD

**Issue by vicbp1** [gravelLab/tracts#32]
Hi all, 
Thank you for developing this amazing software
I am trying to run tracts2 but I am running into some issues 

after creating a conda env and installing tracts, I tried to run the example
The first problem was :

**AttributeError: module 'tracts' has no attribute 'driver**

This was solved by including from tracts import driver in the Python script

Same problem with ParametrizedDemography (I need it to change the name of parametrized_demography to ParametrizedDemography)

However, now I have this issue (on Mac) that I don't know how to solve:

**ImportError: cannot import name 'PhaseTypeDistribution' from 'tracts'**

and on my server (linux), I have the following:

**ImportError: cannot import name 'logs' from partially initialized module 'tracts' (most likely due to a circular import) (/local/chib/toconnor_grp/victor/miniconda3/envs/RunningJasmine/envs/tracts/lib/python3.12/site-packages/tracts/__init__.py)**

Please can you help me with this?
Have a great day!

**Comment by Penglanhui** [comment]
Hi, 
I have the same issue of circular import. 
Here's mine:
    **from tracts import logs
ImportError: cannot import name 'logs' from partially initialized module 'tracts' (most likely due to a circular import) (/share/user/software/tracts/tracts/__init__.py)**

I solved it by editting the init.py script, and here's my editted script:

**import sys
from pathlib import Path
sys.path.insert(1, str(Path(__file__).parent.parent))

from tracts.core import *
from tracts.parametrized_demography import ParametrizedDemography, FixedAncestryDemography
from tracts import legacy_models
from tracts import driver
#from tracts import logs
from tracts import legacy
'''
from core import *
from parametrized_demography import ParametrizedDemography, FixedAncestryDemography
import legacy_models
import driver
import logs
'''


#from tracts.driver import run_tracts

run_tracts = driver.run_tracts

def show_INFO():
        from tracts import logs
        return logs.show_INFO()**

It might help you.
Best,
Lanhui

**Comment by sgravel** [comment]
Hi Victor, 

Thanks for the bug report! I have fixed the issue in the devel branch. I used code recovered from a programmer who has left the lab, so I still need to do some testing before adding this to the main branch, but you can see if that works for you in the meantime.

**Comment by Serdiuk-Andrii** [comment]
This issue has been fixed, everything should work now after pulling the changes and reinstalling the package. If the problem persists, consider opening a new issue
